import os
import sys
import argparse
import glob
import pandas as pd
from rdkit import Chem
from roshambo2 import Roshambo2

def main():
    parser = argparse.ArgumentParser(description="Chunked GPU alignment using ROSHAMBO2 with reliable file-based stitching.")
    parser.add_argument("--query", required=True, help="Input SDF file containing the 3D queries (e.g., zinc_queries_suffixed.sdf)")
    parser.add_argument("--target", required=True, help="Target HDF5 file containing the in-house library (e.g., ETP_cpds_clean.h5)")
    parser.add_argument("--output", default="master_scores.csv", help="Final stitched CSV output filename")
    parser.add_argument("--chunk_size", type=int, default=150, help="Number of queries to process per batch (default: 150)")
    parser.add_argument("--keep_temp", action="store_true", help="Keep the individual query CSVs generated by Roshambo")
    
    args = parser.parse_args()

    print(f"Reading {args.query} and splitting into chunks of {args.chunk_size}...")
    
    try:
        supplier = Chem.ForwardSDMolSupplier(args.query, removeHs=False)
    except OSError:
        print(f"Error: Could not find or open input file '{args.query}'")
        sys.exit(1)
        
    chunk_idx = 1
    current_chunk_mols = []

    # --- PART 1: CHUNK PROCESSING ---
    for mol in supplier:
        if mol is not None:
            current_chunk_mols.append(mol)
            
        if len(current_chunk_mols) == args.chunk_size:
            process_chunk(current_chunk_mols, chunk_idx, args.target)
            chunk_idx += 1
            current_chunk_mols = []
            
    if current_chunk_mols:
        process_chunk(current_chunk_mols, chunk_idx, args.target)

    # --- PART 2: FILE-BASED STITCHING ---
    print("\n--- All chunks processed. Initiating file-based stitching ---")
    
    csv_files = glob.glob("scores_query_*.csv")
    
    if not csv_files:
        print("\nFatal Error: No individual score files found! Roshambo may have failed to write them.")
        sys.exit(1)
        
    print(f"Found {len(csv_files)} individual score files. Loading into RAM...")
    
    all_dataframes = []
    
    for file in csv_files:
        try:
            df = pd.read_csv(file)
            
            # Extract the unique ZINC ID from the filename
            base_name = os.path.basename(file)
            query_id = base_name.replace("scores_query_", "").replace(".csv", "")
            
            # Inject the query ID into the spreadsheet if it's missing
            if 'Query_ID' not in df.columns:
                df.insert(0, 'Query_ID', query_id)
                
            all_dataframes.append(df)
            
        except Exception as e:
            print(f"Could not read {file}: {e}")
            
    print("Stitching matrices together...")
    master_df = pd.concat(all_dataframes, ignore_index=True)
    
    # Sort the final master list to put the absolute best overlap scores at the top
    if 'ComboTanimoto' in master_df.columns:
        print("Sorting by ComboTanimoto score...")
        master_df = master_df.sort_values(by='ComboTanimoto', ascending=False)
    elif 'ShapeTanimoto' in master_df.columns:
        print("Sorting by ShapeTanimoto score...")
        master_df = master_df.sort_values(by='ShapeTanimoto', ascending=False)
    
    master_df.to_csv(args.output, index=False)
    print(f"SUCCESS! Master scores saved to {args.output}")

    # --- PART 3: CLEANUP ---
    if not args.keep_temp:
        print("Cleaning up temporary chunk files...")
        for file in csv_files:
            try:
                os.remove(file)
            except OSError:
                pass
        print("Cleanup complete. Workspace is clean.")
    else:
        print("Temp files retained due to --keep_temp flag.")


def process_chunk(mols, chunk_idx, target_h5):
    chunk_filename = f"temp_query_chunk_{chunk_idx}.sdf"
    
    # Write the small batch to disk for ROSHAMBO to read
    writer = Chem.SDWriter(chunk_filename)
    for m in mols:
        writer.write(m)
    writer.close()
    
    print(f"\n--- Launching GPU Alignment for Chunk {chunk_idx} ({len(mols)} poses) ---")
    try:
        aligner = Roshambo2(chunk_filename, target_h5, color=True)
        
        # We no longer care what Python returns here. 
        # We just execute it so the backend writes the CSVs to disk automatically.
        aligner.compute(backend='cuda', n_gpus=1)
        
    except Exception as e:
        print(f"Error during chunk {chunk_idx}: {e}")
    finally:
        # Clean up the temp input file
        if os.path.exists(chunk_filename):
            os.remove(chunk_filename)

if __name__ == "__main__":
    main()