import csv
import argparse
from rdkit import Chem
from rdkit.Chem import Descriptors, rdMolDescriptors
from rdkit import RDLogger

# Setup command line argument parsing
parser = argparse.ArgumentParser(description="Extract, calculate, and deduplicate hits from a screened SDF file.")
parser.add_argument("-i", "--input", required=True, help="The raw SDF file generated by the screening script.")
parser.add_argument("-o", "--output", required=True, help="The name of the final CSV report you want to generate.")
args = parser.parse_args()

RDLogger.DisableLog('rdApp.*')

input_sdf = args.input
output_csv = args.output

print(f"Extracting and deduplicating data from {input_sdf}...")

suppl = Chem.SDMolSupplier(input_sdf)
best_poses = {} 
score_tag_name = None

for mol in suppl:
    if mol is None:
        continue

    comp_id = mol.GetProp('_Name') if mol.HasProp('_Name') else "Unknown_ID"

    if score_tag_name is None:
        for prop in mol.GetPropNames():
            if "score" in prop.lower() or "fit" in prop.lower():
                score_tag_name = prop
                break
    
    if score_tag_name is None or not mol.HasProp(score_tag_name):
        continue

    score = float(mol.GetProp(score_tag_name))

    mw = Descriptors.MolWt(mol)
    logp = Descriptors.MolLogP(mol)
    rot_bonds = rdMolDescriptors.CalcNumRotatableBonds(mol)

    mol_data = {
        "Compound_ID": comp_id,
        "Fit_Score": round(score, 4),
        "Mol_Weight": round(mw, 2),
        "LogP_Solubility": round(logp, 2),
        "Rotatable_Bonds": rot_bonds
    }

    if comp_id not in best_poses:
        best_poses[comp_id] = mol_data
    else:
        if score > best_poses[comp_id]["Fit_Score"]:
            best_poses[comp_id] = mol_data

results = list(best_poses.values())
results.sort(key=lambda x: x['Fit_Score'], reverse=True)

print(f"Found {len(results)} unique compounds.")
print(f"Writing clean list to {output_csv}...")

with open(output_csv, mode='w', newline='') as file:
    headers = ["Compound_ID", "Fit_Score", "Mol_Weight", "LogP_Solubility", "Rotatable_Bonds"]
    writer = csv.DictWriter(file, fieldnames=headers)
    writer.writeheader()
    writer.writerows(results)

print(f"Report generation complete! Saved to {output_csv}.")