import pandas as pd
import glob
import os

def main():
    # Find all the individual CSV files generated by the ROSHAMBO2 C++ backend
    csv_files = glob.glob("scores_query_*.csv")
    
    if not csv_files:
        print("No score files found! Make sure you are in the directory with the CSVs.")
        return
        
    print(f"Found {len(csv_files)} individual score files. Loading into RAM...")
    
    all_dataframes = []
    
    for file in csv_files:
        try:
            df = pd.read_csv(file)
            
            # Extract the unique ZINC ID from the filename
            # e.g., "scores_query_ZINC000000874810_50.csv" -> "ZINC000000874810_50"
            base_name = os.path.basename(file)
            query_id = base_name.replace("scores_query_", "").replace(".csv", "")
            
            # Inject the query ID into the spreadsheet if it's missing
            if 'Query_ID' not in df.columns:
                df.insert(0, 'Query_ID', query_id)
                
            all_dataframes.append(df)
            
        except Exception as e:
            print(f"Could not read {file}: {e}")
            
    print("Stitching matrices together...")
    master_df = pd.concat(all_dataframes, ignore_index=True)
    
    # Sort the final master list to put the absolute best overlap scores at the top
    if 'ComboTanimoto' in master_df.columns:
        print("Sorting by ComboTanimoto score...")
        master_df = master_df.sort_values(by='ComboTanimoto', ascending=False)
    elif 'ShapeTanimoto' in master_df.columns:
        print("Sorting by ShapeTanimoto score...")
        master_df = master_df.sort_values(by='ShapeTanimoto', ascending=False)
    
    output_file = "ZINC_ETP_master_scores.csv"
    master_df.to_csv(output_file, index=False)
    
    print("\n--- Processing Complete ---")
    print(f"Successfully stitched {len(csv_files)} files.")
    print(f"Total alignment pairs evaluated: {len(master_df)}")
    print(f"Master file saved to: {output_file}")

if __name__ == "__main__":
    main()